/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article { 'title' : string, 'excerpt' : string }
export type StepStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UpgradeStep {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'tips' : string,
  'description' : string,
  'warnings' : string,
}
export interface _SERVICE {
  'addArticle' : ActorMethod<[string, string], bigint>,
  'addRequirement' : ActorMethod<[string, string], undefined>,
  'addStep' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'deleteRequirement' : ActorMethod<[string], undefined>,
  'deleteStep' : ActorMethod<[bigint], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllRequirements' : ActorMethod<[], Array<[string, string]>>,
  'getAllSteps' : ActorMethod<[], Array<UpgradeStep>>,
  'getUserProgress' : ActorMethod<[], Array<[bigint, StepStatus]>>,
  'resetProgress' : ActorMethod<[], undefined>,
  'updateArticle' : ActorMethod<[bigint, string, string], undefined>,
  'updateProgress' : ActorMethod<[bigint, StepStatus], undefined>,
  'updateRequirement' : ActorMethod<[string, string], undefined>,
  'updateStep' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];