/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({ 'title' : IDL.Text, 'excerpt' : IDL.Text });
export const UpgradeStep = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'tips' : IDL.Text,
  'description' : IDL.Text,
  'warnings' : IDL.Text,
});
export const StepStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});

export const idlService = IDL.Service({
  'addArticle' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addRequirement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStep' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'deleteRequirement' : IDL.Func([IDL.Text], [], []),
  'deleteStep' : IDL.Func([IDL.Nat], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllRequirements' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllSteps' : IDL.Func([], [IDL.Vec(UpgradeStep)], ['query']),
  'getUserProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, StepStatus))],
      ['query'],
    ),
  'resetProgress' : IDL.Func([], [], []),
  'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateProgress' : IDL.Func([IDL.Nat, StepStatus], [], []),
  'updateRequirement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStep' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({ 'title' : IDL.Text, 'excerpt' : IDL.Text });
  const UpgradeStep = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'tips' : IDL.Text,
    'description' : IDL.Text,
    'warnings' : IDL.Text,
  });
  const StepStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  
  return IDL.Service({
    'addArticle' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addRequirement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addStep' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'deleteRequirement' : IDL.Func([IDL.Text], [], []),
    'deleteStep' : IDL.Func([IDL.Nat], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllRequirements' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllSteps' : IDL.Func([], [IDL.Vec(UpgradeStep)], ['query']),
    'getUserProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, StepStatus))],
        ['query'],
      ),
    'resetProgress' : IDL.Func([], [], []),
    'updateArticle' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateProgress' : IDL.Func([IDL.Nat, StepStatus], [], []),
    'updateRequirement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStep' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };