/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpgradeStep {
    id: bigint;
    title: string;
    order: bigint;
    tips: string;
    description: string;
    warnings: string;
}
export interface Article {
    title: string;
    excerpt: string;
}
export enum StepStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    addArticle(title: string, excerpt: string): Promise<bigint>;
    addRequirement(key: string, value: string): Promise<void>;
    addStep(title: string, description: string, tips: string, warnings: string, order: bigint): Promise<bigint>;
    deleteArticle(id: bigint): Promise<void>;
    deleteRequirement(key: string): Promise<void>;
    deleteStep(id: bigint): Promise<void>;
    getAllArticles(): Promise<Array<Article>>;
    getAllRequirements(): Promise<Array<[string, string]>>;
    getAllSteps(): Promise<Array<UpgradeStep>>;
    getUserProgress(): Promise<Array<[bigint, StepStatus]>>;
    resetProgress(): Promise<void>;
    updateArticle(id: bigint, title: string, excerpt: string): Promise<void>;
    updateProgress(stepId: bigint, status: StepStatus): Promise<void>;
    updateRequirement(key: string, value: string): Promise<void>;
    updateStep(id: bigint, title: string, description: string, tips: string, warnings: string, order: bigint): Promise<void>;
}
import type { StepStatus as _StepStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addArticle(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addArticle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArticle(arg0, arg1);
            return result;
        }
    }
    async addRequirement(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRequirement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRequirement(arg0, arg1);
            return result;
        }
    }
    async addStep(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStep(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStep(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteRequirement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRequirement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRequirement(arg0);
            return result;
        }
    }
    async deleteStep(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStep(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStep(arg0);
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return result;
        }
    }
    async getAllRequirements(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequirements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequirements();
            return result;
        }
    }
    async getAllSteps(): Promise<Array<UpgradeStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSteps();
            return result;
        }
    }
    async getUserProgress(): Promise<Array<[bigint, StepStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetProgress(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetProgress();
            return result;
        }
    }
    async updateArticle(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProgress(arg0: bigint, arg1: StepStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgress(arg0, to_candid_StepStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgress(arg0, to_candid_StepStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRequirement(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequirement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequirement(arg0, arg1);
            return result;
        }
    }
    async updateStep(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStep(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStep(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_StepStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StepStatus): StepStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _StepStatus]): [bigint, StepStatus] {
    return [
        value[0],
        from_candid_StepStatus_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): StepStatus {
    return "notStarted" in value ? StepStatus.notStarted : "completed" in value ? StepStatus.completed : "inProgress" in value ? StepStatus.inProgress : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _StepStatus]>): Array<[bigint, StepStatus]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function to_candid_StepStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StepStatus): _StepStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StepStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == StepStatus.notStarted ? {
        notStarted: null
    } : value == StepStatus.completed ? {
        completed: null
    } : value == StepStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
